// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgIehZfmzo3uSQTluH-qLcmZrTq5mfCeU',
    appId: '1:387859511366:web:20ba6f48b82f556e6bb247',
    messagingSenderId: '387859511366',
    projectId: 'water-tracker-acbfb',
    authDomain: 'water-tracker-acbfb.firebaseapp.com',
    storageBucket: 'water-tracker-acbfb.firebasestorage.app',
    measurementId: 'G-YLHMS3CBYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2XEcytvvf7udd5f1_c2t6XsjFAN7rUG0',
    appId: '1:387859511366:android:eebdc5316c6dce676bb247',
    messagingSenderId: '387859511366',
    projectId: 'water-tracker-acbfb',
    storageBucket: 'water-tracker-acbfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-w4V3nSbHLP-pnUo-4DzDDMZRQo_6fI',
    appId: '1:387859511366:ios:b3366f56f4a2d6ae6bb247',
    messagingSenderId: '387859511366',
    projectId: 'water-tracker-acbfb',
    storageBucket: 'water-tracker-acbfb.firebasestorage.app',
    iosBundleId: 'com.example.watertracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg-w4V3nSbHLP-pnUo-4DzDDMZRQo_6fI',
    appId: '1:387859511366:ios:b3366f56f4a2d6ae6bb247',
    messagingSenderId: '387859511366',
    projectId: 'water-tracker-acbfb',
    storageBucket: 'water-tracker-acbfb.firebasestorage.app',
    iosBundleId: 'com.example.watertracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgIehZfmzo3uSQTluH-qLcmZrTq5mfCeU',
    appId: '1:387859511366:web:79e390547fc85c086bb247',
    messagingSenderId: '387859511366',
    projectId: 'water-tracker-acbfb',
    authDomain: 'water-tracker-acbfb.firebaseapp.com',
    storageBucket: 'water-tracker-acbfb.firebasestorage.app',
    measurementId: 'G-28YRGCN96G',
  );
}
